words = [
"de espaldas", "a popa", "abandonado", "avergonzado","aberrante", "aborrecible", 
"permanente", "abyecto","ardiente","capaz","anormal","abordo","aborigen","abortivo",
"abundante","abrasivo","abrupto","ausente","absorbido","absorbente","abstraido","absurdo",
"abundante","abusivo","aceptable","accesible","accidental","preciso","acido","acustico","acre",
"realmente","adhoc","inflexible","adaptable","adicto","adhesivo","contiguo","adorable",
"aventurero","miedo","agresivo","agonizante","agradable","adelante","entreabierto","alcoholico",
"alerta","igual","vivo","presunto","seductor","distante","sorprendente","ambiguo","ambicioso",
"divertido","divertido","divertido","antiguo","enojado","animado","molesto","molesto","ansioso",
"apatico","acuatico","aromatico","arrogante","avergonzado","aspirante","variado","asombroso",
"atractivo","auspicioso","automatico","disponible","promedio","despierto","consciente","impresionante",
"horrible","axiomatico","malo","barbaro","timido","obsceno","hermoso","conveniente","beligerante",
"beneficioso","doblado","loco","mejor","mejor","desconcertado","grande","ondulante","pequeño",
"amargo","extraño","negro","blanco y negro","sangriento","azul","ojos azules","sonrojar",
"hirviendo","grosero","aburrido","aburrido","rebotante","ilimitado","inteligente","descarado",
"valiente","musculoso","quebradizo","ventoso","breve","brillante","brillante","amplio",
"roto","marron","bacheado","fornido","bullicioso","ocupado","cauteloso","calculador","insensible",
"tranquilo","capaz","caprichoso","cuidadoso","descuidado","cuidadoso","cauteloso","incesante","cierto",
"cambiable","encantador","barato","alegre","jefe quimico","infantil","frio","caballero",
"gordito","grueso","con clase","limpio","claro","inteligente","enclaustrado","nublado",
"cerrado","torpe","desordenado","coherente","frio","colorido","colosal","combativo","comodo",
"comun","completo","complejo","preocupado","condenado","confundido","consciente","arrullo","cool",
"cooperativo","coordinado","valiente","cobarde","malhumorado","cobarde","loco","espeluznante",
"torcido","abarrotado","cruel","mimoso","culto","engorroso","curioso","rizado","curvo",
"curvados","cortado","lindo","lindo","cinico","diario","dañado","dañino","humedo","peligroso",
"apuesto","oscuro","deslumbrante","muerto","inexpresivo","ensordecedor","querido","elegante","decisivo",
"decoroso","profundo","profundamente","derrotado","defectuoso","desafiante","delicado","delicioso",
"encantador","demoniaco","delirante","dependiente","deprimido","trastornado","descriptivo","desierto",
"detallado","determinado","diabolico","didactico","diferente","dificil","diligente","horrible","sucio",
"desagradable","desastroso","discreto","disgustado","repugnante","desilusionado","prescindible","distinto",
"perturbado","divergente","mareado","dominante","dudoso","monotono","draconiano","dramatico","triste",
"borracho","seco","opaco","polvoriento","dinamico","disfuncional","ansioso","temprano","ensordecedor",
"terroso","facil","comible","economico","educado","eficaz","eficiente","ocho","elastico","alegre",
"anciano","electrico","elegante","elfo","elite","avergonzado","eminente","vacio","encantado",
"encantador","alentador","soportable","energetico","enorme","entretenido","entusiasta",
"envidioso","ecuable","igual","erguido","erratico","etereo","evanescente","evasivo","incluso",
"excelente","emocionado","emocionante","exclusivo","exotico","caro","extra grande","extra pequeño",
"exuberante","exultante","fabuloso","descolorido","desmayado","justo","fiel","falaz","falso","familiar",
"famoso","fanatico","elegante","fantastico","lejos","fascinado","gordo","rapido","defectuoso","temeroso",
"intrepido","debil","fingido","hembra","fertil","festivo","pocos","feroz","sucio","fino","melindroso",
"primero","cinco","fijo","flagrante","escamoso","llamativo","plano","impecable","endeble","frivolo","florido",
"esponjoso","revoloteando","espumoso","tonto","precedente","olvidadizo","afortunado","cuatro","fragil",
"fragil","frenetico","libre","congelado","frecuente","fresco","inquieto","amistoso","asustado",
"aterrador","full","funcional","divertido","furtivo","futuro","futurista","borroso","locuaz",
"lucrativo","gamy","boquiabierto","locuaz","llamativo","general","gentil","gigante","vertiginoso","dotado",
"gigantesco","glamuroso","reluciente","simplista","reluciente","glorioso","brillante","piadoso","bueno",
"tonto","hermoso","elegante","grandioso","agradecido","gratis","gris","grasoso","genial","codicioso","verde",
"gris","doliente","groovy","grotesco","gruñon","gruñon","espantoso","gruñon","guardado","inocente","credulo",
"gustoso","gutural","habitual","mitad","santificado","hermoso","vacilante","hermosamente","practico","colgado",
"desventurado","feliz","duro","dificil de encontrar","armonioso","duro","odioso",
"embriagador","saludable","desgarrador","celestial","pesado","infernal","servicial","indefenso",
"vacilante","espantoso","alto","altisonante","tono agudo","hilarante","silbidos",
"historico","holistico","hueco","sin hogar","hogareño","honorable","horrible",
"hospitalario","caliente","enorme","descomunal","monotono","humoristico","hambriento","apresurado","dolido",
"silencioso","ronco","hipnotico","histerico","asqueroso","helado","idiota","ignorante","enfermo","ilegal",
"desdichado","mal informado","ilustre","imaginario","inmenso","inminente","imparcial",
"imperfecto","descortes","importante","importado","imposible","incandescente",
"incompetente","poco concluyente","trabajador","increible","barato","infame",
"innato","inocente","curioso","insidioso","instintivo","inteligente","interesante","interno",
"invencible","enfadado","irritante","picante","hastado","irregular","jazz","celoso","nervioso","desempleado",
"alegre","juvenil","jugoso","jugoso","confundido","nervioso","juvenil","kaput","agudo",
"amable","de buen corazon","amablemente","nudoso","saber","conocido","conocido",
"trabajado","desganado","carente","cojo","lamentable","languido","grande","ultimo",
"risible","prodigo","perezoso","flaco","aprendido","izquierda","legal","letal","nivel",
"ligero","ligero","alterado","ligero","nivel","pequeñito","animado","animado","viviente",
"solitario","largo","anhelante","largo plazo","suelto","desequilibrado","ruidoso",
"gruñon","encantador","amoroso","bajo","humilde","afortunado","ridiculo","grumoso","exuberante",
"mentiroso","lirico","macabro","macho","desesperante","locamente","magenta","magnifico",
"majestuoso","improvisado","masculino","maligno","mamut","maniaco","muchos","marcado","masivo",
"casado","maravilloso","material","materialista","maduro","maduro","miserable","carnoso","medico",
"manso","melodico","derretido","misericordioso","mero","desordenado","poderoso","militar","lechoso",
"sin sentido","miniatura","menor","malhechor","brumoso","gemidos","moderno","mohoso",
"trascendental","inmovil","montañoso","confuso","mundano","turbio","blando","mudo","misterioso","ingenuo",
"pañal","estrecho","desagradable","natural","travieso","nauseoso","cerca","ordenado","nebuloso",
"necesario","innecesario","necesitado","vecino","nervioso","nuevo","siguiente","agradable","habil",        
"nueve","agil","silencioso","ruidoso","indiferente","anodino","sin parar","normal",
"nostalgico","entrometido","nocivo","nulo","innumerables","numerosos","nutritivo","chiflado","tonto",
"obediente","obediente","obeso","desagradable","obsceno","obsequioso","observante","obsoleto",
"obtenible","oceanico","extraño","poco convencional","viejo","anticuado","omnisciente",
"uno","oneroso","abierto","opuesto","optimo","naranja","ordinario","organico","osificado","extrovertido",
"escandaloso","sobresaliente","ovalado","demasiado confiado","alegre","sobrevalorado",
"abierto","sobreexcitado","doloroso","escrupuloso","palido","miserable","panoramico","paralelo","seco",
"parsimonioso","pasado","pastoral","patetico","pacifico","penitente","perfecto","periodico","permisible",
"perpetuo","pequeño","pequeño","fobico","fisico","agradable","picayune","palezoso","plausible","planta",
"plastico","plausible","rosado","sencillo","sin sentido","preparado","educado",
"politico","pobre","posesivo","posible","poderoso","precioso","premium","presente",
"bonito","anterior","caro","espinoso","privado","probable","productivo","profuso","protector","orgulloso",
"psicodelico","psicotico","hinchado","publico","insignificante","morado","ronroneando","agresivo","desconcertado",
"desconcertante","curandero","pintoresco","peleon","cuestionable","rapido",
"el mas rapido","tranquilo","peculiar","quijotesco","interrogante","rabioso","racial",
"desgarrado","lluvioso","revoltoso","desenfrenado","raro","raro","rasposo","ratonado","listo","real",
"rebelde","receptivo","recondito","rojo","redundante","reflexivo","regular","aliviado","notable",
"recordante","repulsivo","resuelto","resonante","responsable","retorico","rico","correcto","justo",
"legitimo","rigido","maduro","lujoso","tostado","robusto","romantico","espacioso","podrido","aspero",
"redondo","real","rubicundo","grosero","despiadado","rural","despiadado","sable","seguro","salado",
"seguro","rustico","sabroso","sable","triste ","escandaloso","escaso","asustado",
"espantoso","disperso","cientifico","brillante","esqueletico","chillido","segundo",
"de segunda mano","secreto","secreto","sedado","selectivo","egoista","separado","serio",
"peludo","temblor","afilado","brillante","estremecimiento","impactante","corto","estridente","callado",
"timido","enfermo","silencioso","silencioso","sedoso","tonto","simple","simplista","sincero","seis",
"sedoso","tonto","somnoliento","delgado","baboso","descuidado","lento","pequeño","inteligente","maloliente",
"sonriente","smog","suave","furtivo","esnob","mocoso","suave","empapado","solido","sombrio","sofisticado",
"sordido","dolorido","dolorido","acido","espumoso","especial","espectacular","picante","puntiagudo",
"espiritual","rencoroso","esplendido","espeluznante","impecable","manchado","irregular","espureo",
"escualido","cuadrado","chillido","aprensivo","estacar","estabilizar","estabilizar","estabilizar",
"estabilizar","escarpado","escarpado","estatuoso","escarpado","estereotipado","pegajoso","rigido",
"estimulante","tacaño","tormentoso","recto","extraño","rayado","fuerte","estupendo","estupido",
"robusto","atenuado","posterior","sustancial","exitoso","sucinto","repentino","enfurruñado","super",
"magnifico","superficial","supremo","elegante","dulce","sofocante","rapido","sintomatico",
"sinonimo","tabu","tacito","hortera","talento","alto","manso","bronceado","tangible","picante","tarta",
"de buen gusto", "insipido", "sabroso", "de mal gusto", "lloroso", "tedioso", 
"pequeñito", "pequeño-pequeño", "contando","temporal","diez","tierno","tenso","tenue",
"terrible","estupendo","probado","irascible","agradecido","terapeutico","grueso","delgado",
"pensable","tercero","sediento","sediento","pensativo","imprudente","amenazante",
"tres","tronador","ordenado","apretado","tacaño","pequeño","cansado","cansado",
"dungoso","torpido","duro","altisimo","tranquilo","basura","tremendo","complicado","trillado","preocupado",
"truculento","verdadero","veraz","dos","tipico","ubicuo","feo","ultra","incapaz",
"irresponsable","desavisado","desarmado","impropio","imparcial","descubierto","entendido","indeseable",
"desigual","desigual","desigual","insalubre","desinteresado","unico","descuidado","desconocido","antinatural",
"rebelde","antiestetico","inadecuado","desordenado","sin usar","inusual",
"dificil de manejar","no escrito","optimista","engreido","molesto","tenso",
"usado","util","inutil","utopico","absoluto","vacio","vagabundo","vago",
"valiosos","varios","vastos","venenosos","verdes","versificados","victoriosos","vigorosos","violentos",
"violeta","vivaz","mudo","volatil","voraz","vulgar","chiflado","chiflado","esperando",
"despierto","errante","queriente","guerreroso","calido","despilfarrador","aguado","debil","rico",
"cansado","bien arreglado","bien hecho","acomodado","acomodado","mojado","caprichoso",
"susurrando","blanco","entero","al por mayor","malvado","ancho",
"con los ojos muy abiertos","movimiento","salvaje","dispuesto","ventoso","nervudo",
"sabio","melancolico","ingenioso","desconsolado","femenino","maravilloso","de madera",
"mareado","realizable","preocupado","inutil","iracundo","desdichado","equivocado","ironico",
"amarillo","docil","joven","juvenil","delicioso","estrafalario","celoso",
"energico","zippy","zonked","cuenta","triunfador","acustica","acto","accion","actividad","actor","adicion",
"adaptacion","anuncio","consejos","secuelas","tarde","pensamiento de ultimo momento",
"acuerdo","aire","avion","aeropuerto","alarma","cantidad","diversion","angulo","animal","hormigas",
"aparato","ropa","aparato","aprobacion","arco","argumento","aritmetica","brazo","ejercito",
"arte","ataque","atraccion","autoridad","tia","bebes","bebe","bolso","baloncesto","baloncesto",
"baloncesto","base","base","baloncesto","baloncesto","abeja","baño","batalla","cama","comportamiento",
"creencia","dormitorio","batalla","murcielago","oso","principiante","oso","creer","campanas",
"bayas","bicicleta","bicicletas","cumpleaño","pajaros","nacimiento","mordisco","pajaro",
"bote","bota","bota","bota","caja","bota","boca","hueso","libro","frontera","libros","sangre",
"tabla ","chico","aliento","bombilla","bras","bras","ladrillo","puente","hermano",
"burbuja","balde","edificio","rama","reventar","arbustos","calendario","boton","mantequilla","repollo",
"cable","cactus","pastel","tortas","calendario","camara","campamento",
"cañon","cañon","carruaje","coche","cuidado","gorra","lona","titulo","tarjeta","tarjeta",
"apio","bodega","cementerio","causa","causa","cementerio","causa","cementerio","causa",
"cementerio","casting","cambio","canal","queso","cerezas","cereza","ajedrez","pollo","pollos","nadan",
"barbilla","iglesia","almeja","almeja","clase","collar","entrenador","club","carbon","costa",
"telareda","trebol","taladrea ","color","comite","compañia","comparacion","competencia",
"condicion","conexion","control","cocinero","cobre","creador","crema","cubrir","crack",
"cracker","maiz","pais","crema","tos","criatura","credito","crimen","corriente","cuervo",
"curva","multitud","cuna","copa","corriente","almohadon","deuda","dia","diseñado","hija",
"muerte","venado","diseño","grado","deseo","escritorio","destruccion","detalle","desarrollo",
"digestion","cena","dinosaurios","direccion","suciedad","descubrimiento","discusion",
"distancia","distribucion","division","doctor","doctor","perro","perros","burro",
"cajon","centro de la ciudad","drenaje","bebida","muñecas","muñecas","pato","puerta",
"vestido","patos","borde","educacion","efecto","huevo","huevos","oeja","terremoto","codo",
"fin","motor","error","evento","ejemplo","intercambio","existencia","expansion","experiencia",
"experto","ojo","ojos","cara","campo","caer","dedo","dedo","fuego","granja","miedo","sentimiento",
"caer","campo","colmillo","hecho","hadas","bombero","bandera","carne","flores","llama",
"mosca","niebla","pez","piso","sabor","vuelo ", "amigo","amigos","aves","comida",
"friccion","fuerza","forma","marco","pie","rana","ranas","pliegue ","frente","fruta",
"chicas","combustible","fantasma","gansos","gigantes","guante","jirafas","muebles",
"puerta","vaso","abuelo","abuelo","gobierno","gobernador","grado","grano","abuelo",
"hierba","suelo","uva","armonia","crecimiento","grupo","guitarra","guia","manos",
"manos","pelo","pelo","pistola","puerto","sala ","hoyo","cabeza","calor","cabeza",
"colina","casa","historia","odio","salud","sombrero","vacaciones","gancho","esperanza",
"caliente","caballo","casas","caballos","hidrantes","hospital","hora","hielo",
"humor","manguera","hidratante","hidratante","idea","impulso","ingresos","industria","insectos",
"instrumento","interes","seguros","tinta", "carcel","hierro","invenci\u00f3n","isla",
"mermelada","jugo","joyas","jeans","jugo","beso","hervidor","conocimiento","cuchillo","cordon","gatitos",
"llave","nudo","patada","obrero","rodilla","saltar","carta","cuero","lenguaje","lampara","lago","lechuga",
"pierna","pierna","risa","tierra","amor","biblioteca","candado","linea","linea","labio","liquido",
"pan","medapelito","mirada","pan", "perdida","bajo","almuerzo","buzon de correo",
"comedor","magia","hombre","madera","maquina","marmol","marca","mascarilla","mercado",
"masa","masas","partido","carne","comida","hombres","leche","memoria","metal","mio",
"medio","mente","ratones","reunion","ministro","menta","minutos","manoplas","mama","mono","mes",
"niebla","madre","movimiento","mes","niebla","aguja","boca","cuello","movimiento","musculo",
"nacimiento","nacion","necesidad","nido","nombre","noche","ruido ","norte","avena",
"nota","cuaderno","numero","nuez","observaci\u00f3n","oceano","oferta","oficina","aceite",
"naranja","naranjas","orden","paquete","paquete","pan","parte","panqueque","papel",
"parte","panqueque","parte ","pasajero","boligrafo","imagen","lapiz","mascota","paz",
"pepinillo","persona","pepinillo","paz","pastel","paz","persona ","alfiler",
"avion","cerdos","cerdos","lugar","pizzas","planta","plantaciones","plastico",
"pipas","pipa","arado","bolsillo","contaminacion","juego","placer","parcela","plato","punto",
"veneno","palomitas de maiz","portero","posicion","patata","polvo","poder","precio",
"producir","beneficio","propiedad","prosa","protesta","tirar","bombear","castigo",
"proposito","empujar","cuarzo","cuarzo","pregunta","reina","tranquilo","tranquilo",
"pua","edredon","membrillo","conejo","conejos","ferrocarril","lluvia","tormenta","rastrillo","alcance",
 "rata","tasa","rayo","lectura","razon","recibo","recreo","rayo","reaccion","relacion",
"religion","anillos","representante","solicitud","respeto","recompensa","ritmo","arroz","acertijo","rifle",
"descanso","recompensa","rico","carretera","camino","correr","varilla","roca","habitacion","regla",
"roca","roca","roca","roca","roca","roca","roca","roca","roca","regla","roca","roca",
"rutina ","saco","vela","arena","escamas","ciencias","escena","espantapajaros","olor",
"mar","mares","sal","martillo","tornillo","asiento","forma","orilla del mar","secretaria",
"seleccion","sentido","siervo","sombra","verguenza","seleccion","acera","barco","barquito",
"camiseta","shock","espancion","hoja","espectacion","lado","estante","tienda","zapato",
"zapatos ","seda","cielo","fregadero","esclavo","hermanas","patinar","piel","plata",
"resbalon","dormir","esclavo","talla ","pendiente","aplastar","estornudar","humo",
"jabon","olor","nieve","serpiente","sociedad","serpiente","calcetin","canciones","chispa",
"espacio","soda","hijo","ordenar","soda","soledad","sonido","aradas ","esponja",
"ardilla","cuchara","estacio3n","estaciones","espuma","espumada","estrella","inicio",
"sello","sello","cuadrado","estacion","acero","estomago","calcetin","guiso","palo",
"palos","piedra","paso","piedra","puntada","tallo","vapor","almacenar","vapor",
"cuento","calle","estufa","extranjero","arroyo","estructura","estiramiento","paja","sustancia","azucar",
"sugerencia","traje","verano","sol","soporte","sorpresa","sueter","nadar","columpio","sistema","mesa","cola",
"hablar","tanque","sabor","enseñanza","equipo","temperamento","temperamento","tendencia","territorio","prueba",
"textura","teoria","cosa","cosas","pensamiento","estremecimiento","garganta","pensamiento","pulgar","trueno",
"billete","cepillo de dientes","dedo del pie","dedos del pie","lata","diente","lengua",
"tomate","titulo","pasta de dientes","comercio","toque","juguetes","pueblo","sendero",
"tren","trenes","vagabundo","transporte","bandeja","tratamiento","arbol","arboles","truco",
"pantalones","problema","pavo","tratamiento","tina","viaje","girar","giro","giran",
"paraguas","ropa interior","unidad","uso","vacaciones","valor","tufo","vegetal",
"velo","vena","verso","vaso","chaleco","vista","visitante","voz","volcan","voleibol",
"agua","caminar","camino","cera","guerra","lavar","relojar","mirar","ola","olas",
"pared","riqueza","viaje ","clima","semana","peso","rueda","latigo","silbato","salvaje",
"viento","ventana","vino","ala","invierno","alambre","deseo","escritora","gusano",
"herida","lana","madera","mujer","palabra","llave inglesa","trabajo","trabajo ","año",
"cebra","cefiro","cremallera","escritura","hilo","yerno","yugo","zinc","yugo","zoo ",
"añadir","admirar","admitir","aconsejar","permitir","acordar","alertar","permitir","divertir",
"analizar","anunciar","molestar","responder","disculparse","aparecer","aplaudir","agradecer",
"aprobar","argumentar","arreglar","arrestar","llegar","preguntar","adjuntar","atacar","intentar",
"asistir","atraer","evitar","atras","hornear","equilibrar","prohibir","bang","desnudo",
"murcielago","bañarse","batallar","rayo","rogar","comportarse","pertenecer","blanquear","bendecir",
"ciegar","parpadear","borrar","sonrojarse","alardear", "hervir","arco","bomba",
"tornillo","respirar","freno","libro","pedir prestado","respirar","moreton","rama",
"respirar","cepillar","burbuja","golpear","quemar","enterrar","zumbir","calcular",
"llamar","acampar","cuidado","llevar","tallar","causa","desafio","cambiar","cargar","perseguir",
"chequear","aplaudir","masticar","ahorcar","picar","reclamar","aplaudir","limpiar",
"limpias ","acortar","cerrar","entrenador","bobina","colorear","peine","comando",
"comunicar","comparar","competir","quejarse","completar","concentrarse","preocuparse","confesar","confundir",
"conectar","considerar","consistir","contener","continuar","copiar","corregir","contar","cubrir",
"crack","crash","gatear","cruzar","aplastar","llorar","curar","torcer ","curva","ciclo",
"daño","dañar","atreverse","decaer","decidir","decorar","retrasar","entregar","deleitar",
"deleitar","decidir","depender ","describir","desertar","merecer","destruir","detectar",
"desarrollar","no estar de acuerdo","desaparecer","desaprobar","desarmar","descubrir",
"aborrecer","dividir","dudar","ahogar","arrastrar","drenar","gotear","soltar","drenar",
"solucion","vestir","secar","tambor ","polvo","ganar","educar","avergonzar","emplear",
"vaciar","alentar","finalizar","disfrutar","entrar","entretener","escapar","examinar","emocionar",
"excusa","ejercicio","existir","expandir","esperar","explicar","explotar","extender",
"cara","descolorarse","fallar","elegante","abrochar","fichero","fax","fuego","llenar",
"miedo","pelicula","arreglar","flap","flotar","valla","inundacion","flujo","flor",
"doblar","asustar","tonto","fuerza","formar","encontrar","freir","marco","mirada",
"reunir","pegamento","resplandecer","agarrar","rallar","adivinar","agarrar","agarrar","grasa",
"garantizar","guardar","guia","mano","manejar","martillo","saludar","sacar ","suceder",
"acosar","cabeza","calor","ayuda","gancho","esperanza","curar","odio","monton","gancho",
"salto","esperanza" ,"abrazo","tararear","cazar","apurarse","identificar","ignorar",
"imaginar","impresionar","mejorar","incluir","aumentar","influir","informar","inyectar",
"herir","instruir","intentar","interesar","interferir","interrumpir","introducir","inventar",
"invitar","irritar","picar","carcel","broma","jogging","juzgar","matar","juzgar","matar",
"patear","saltar","arrodillarse","unirse","golpe","nudo","etiqueta", "aligerar",
"aprender","aterrizar","escuchar","lamer","mentir","me gusta","listar","tierra","reir",
"lanzar","tierra ","en vivo","cargar", "amor","cerrar","casar","pareja","manejar",
"hombre","largo","marchar","marcar","mirar","parejar","materia","medir","partido","inmiscuirse","derretir",
"memorizar","reparar","estropear","leche","mio","mezclar","gemir","llorar","moverse",
"confundir","taza","multiplicar","asesinato","clavo","aviso","nido","necesidad","nido","nota",
"numero","obedecer","objeto","obtener","obtener","ocurrir ","ofender","ofrecer",
"abrir","deber","deber","paquete","ordenar","paquete","parque","pintar","pase","pegar",
"parte","pintar","pase","rebosar"," ","pausa","picoteo","pedal",
"pelar","peep","realizar","permitir","pegar","lugar","jugar","permitir",
"pinar","planificar","plantar","por favor","pellizcar","telefono","enchufe","punto"
"pok","polaco","pop","poseer","postear","practicar","rezar","predicar","preceder",
"preferir","preparar","presentar" ,"preservar", "presionar","pretender","prevenir",
"imprimir","producir","programar","promesa","proteger","proporcionar","tirar","puñetazo",
"pinchar","castigar","empujar","preguntar","hacer cola","irradiar","lluvia","levantar",
"alcanzar","darse cuenta","recibir","reconocer","registrar","reducir","reflexionar",
"rechazar", "arrepentirse","reinar","rechazar","alegrarse","relajarse","liberar","confiar",
"permanecer","recordar ","recordar","eliminar","reparar","repetir","reemplazar",
"responder","reportar","reproducir","solicitud","rescatar","retirar","retornar","rima",
"enjuagar","arriesgarse","robar","rocar","robar","frotar","ruinar","gobernar","robar",
"robar","robar","satisfacer","navegar","salvar","vio","asustar","dispersar","regañar",
"quemar","raspar","gritar","garabatear","fregar","buscar","sellar","separar",
"servir","atornillar ","sombra","afeitarse","compartir","choque","encogerse de hombros",
"esquiar","refugiarse","pecado","señal","suspiro","comprar","sorbo","comprar ","saltar",
"bofetada","deslizarse","lento","aplastar","fumar","lento","estornudar","oler",
"nieve","remojar","sonar","sonreir ","repuesto","chispa","brillar","brotar","hechizo",
"derramar","estropear","manchar","mancha","spray","sello","sello ","mirar fijamente",
"iniciar","mantener","dirigir","revolver","parar","parar","fortalecer","pasar","puntar",
"tirar","almacenar","tirar","cosa", "sustraer","sustraer","suceder","sugerir","sugerir",
"suministrar","apoyar","suponer","sorpresa","sugerir","suponer","suspender","sustraer",
"sustraer","sustraer","sustraer","sustraer ","interruptor","hablar","domar","tocar",
"probar","provocar","telefono","tentar","aterrorizar","probar","agradecer","descongelar",
"telefono","cosquillas","lazo","tiempo","comercio","trampa","recorrido","neumatico","pista","remolcar",
"transporte","tren","trampa","viajar","trampa","tren ","truco","viaje","trote",
"problema","confiar","descubrir","descubrir","girar","intentar","girar","teclear","desnudar",
"tirar","unir","descomprimir","desordenado","uso","agua","desaparecer","esperar","esperar","querer",
"lamentarse","deambular","querer","lavar","mirar","visitar","visitar","desperdiciar",
"visitar","agua ","saludar","pesar","bienvenido","envolver","envolver","envolver",
"envolverse","envolveran","latigo","giro","preocuparse","preocuparse","preocuparse",
"trabajar","naufragio","luchar","retorcerse","rayos x","bostezar","gritar","zip","zoom"
]
